Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,10 +25,14 @@ jobs:
       - name: Build the C++ file
         run: |
           g++ hello.cpp -o hello
-          ./hello
-       # continue-on-error: true  # This allows the error to show without stopping the process
+          if [ $? -eq 0 ]; then  # Check if g++ was successful
+            ./hello
+          else
+            echo "Build failed: hello.cpp didn't compile."
+            exit 1  # Exit the pipeline with a failure status
+          fi
 
-      - name: Display the output (If it fails)
+      - name: Display the output
         run: |
           if [ -f hello ]; then
             ./hello
